from jsonmanipulations.jsontagvariables import JsonTagVariables
from utility.stringutil import StringUtility

class ConfigParametersValue():

    @classmethod
    def __init__(cls, main_config_obj,
                      dbconnection_config_obj,
                      cloudstorage_connection_config_obj,
                      Fusionjobs_config_obj,
                      log_config_obj,
                      table_config_obj, 
                      load_missing_view_object_config_obj,
                      bipublisher_individual_report_config,
                      import_etl_dependent_csv_config_obj,
                      job_scheduling_parameter_inputs):

        cls.max_threads_count_for_downloading               = main_config_obj.json_val(JsonTagVariables.max_threads_count_for_downloading)
        cls.max_threads_count_for_csv_process               = main_config_obj.json_val(JsonTagVariables.max_threads_count_for_csv_process)
        cls.max_threads_count_for_sil_process               = main_config_obj.json_val(JsonTagVariables.max_threads_count_for_sil_process)
        cls.use_cloud_storage_for_bicc                      = main_config_obj.json_val(JsonTagVariables.use_cloud_storage_for_bicc)
        cls.load_type                                       = main_config_obj.json_val(JsonTagVariables.type_of_load_to_process)
        cls.table_configuration_file_directory              = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.table_configuration_file_directory))
        cls.log_base_directory                              = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.log_base_directory))
        cls.main_log_file_name_format                       = main_config_obj.json_val(JsonTagVariables.log_main_file_name_format)
        cls.log_summary_directory                           = main_config_obj.json_val(JsonTagVariables.log_summary_directory)
        cls.log_download_directory                          = main_config_obj.json_val(JsonTagVariables.log_download_directory)
        cls.log_request_table_directory                     = main_config_obj.json_val(JsonTagVariables.log_request_table_directory)
        cls.log_sdesil_table_directory                      = main_config_obj.json_val(JsonTagVariables.log_sdesil_table_directory)
        cls.log_etl_summary_file                            = main_config_obj.json_val(JsonTagVariables.log_etl_summary_file)
        cls.log_download_summary_file                       = main_config_obj.json_val(JsonTagVariables.log_download_summary_file)
        cls.log_table_summary_file                          = main_config_obj.json_val(JsonTagVariables.log_table_summary_file)
        cls.recovery_enabled_flag                           = main_config_obj.json_val(JsonTagVariables.recovery_enabled_flag)
        cls.tables_recovery_status_file                     = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.tables_recovery_status_file))
        cls.recovery_base_directory                         = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.recovery_base_directory))
        cls.recovery_download_queued_list                   = main_config_obj.json_val(JsonTagVariables.recovery_download_queued_list)
        cls.recovery_download_completed_list                = main_config_obj.json_val(JsonTagVariables.recovery_download_completed_list)
        cls.recovery_csv_process_queued_list                = main_config_obj.json_val(JsonTagVariables.recovery_csv_process_queued_list)
        cls.recovery_csv_completed_full_list                = main_config_obj.json_val(JsonTagVariables.recovery_csv_completed_full_list)
        cls.recovery_sil_queued_list                        = main_config_obj.json_val(JsonTagVariables.recovery_sil_queued_list)
        cls.recovery_sil_completed_list                     = main_config_obj.json_val(JsonTagVariables.recovery_sil_completed_list)
        cls.recovery_status                                 = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.recovery_status))
        cls.cert_csv_import_parameters                      = main_config_obj.json_val(JsonTagVariables.cert_csv_import_parameters)
        cls.cert_csv_enabled_flag                           = main_config_obj.json_val(JsonTagVariables.cert_csv_enabled_flag)
        cls.certfication_csv_directory_file_stored          = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.certfication_csv_directory_file_stored))
        cls.ledger_filter                                   = main_config_obj.json_val(JsonTagVariables.ledger_filter)
        cls.smtp_server_host                                = main_config_obj.json_val(JsonTagVariables.email_server_host)
        cls.smtp_server_port                                = main_config_obj.json_val(JsonTagVariables.email_server_port)
        cls.email_sender_emailid                            = main_config_obj.json_val(JsonTagVariables.email_sender_emailid)
        cls.email_receiver_list                             = main_config_obj.json_val(JsonTagVariables.email_receiver_list)
        cls.email_inline_attachements                       = main_config_obj.json_val(JsonTagVariables.email_inline_attachements)
        cls.email_attachements                              = main_config_obj.json_val(JsonTagVariables.email_attachements)
        cls.email_subjectline                               = main_config_obj.json_val(JsonTagVariables.email_subjectline)
        cls.retry_count_in_cloud_download                   = main_config_obj.json_val(JsonTagVariables.retry_count_in_cloud_download)
        cls.retry_time_when_no_requestid_found              = main_config_obj.json_val(JsonTagVariables.retry_time_when_no_requestid_found)
        cls.wait_time_when_no_requestid_found               = main_config_obj.json_val(JsonTagVariables.wait_time_when_no_requestid_found)
        cls.retry_count_for_comparing_md5                   = main_config_obj.json_val(JsonTagVariables.retry_count_for_comparing_md5)
        cls.bicc_base_directory                             = main_config_obj.json_val(JsonTagVariables.bicc_base_directory)
        cls.process_sil_folder_format                       = main_config_obj.json_val(JsonTagVariables.process_sil_folder_format)
        cls.sil_log_base_directory                          = main_config_obj.json_val(JsonTagVariables.sil_log_base_directory)
        cls.recovery_biprdep_table_queued_list              = main_config_obj.json_val(JsonTagVariables.recovery_biprdep_table_queued_list)
        cls.recovery_biprdep_table_completed_list           = main_config_obj.json_val(JsonTagVariables.recovery_biprdep_table_completed_list)
        cls.recovery_bipreport_download_queued_list         = main_config_obj.json_val(JsonTagVariables.recovery_bipreport_download_queued_list)
        cls.recovery_bipreport_download_completed_list      = main_config_obj.json_val(JsonTagVariables.recovery_bipreport_download_completed_list)
        cls.recover_biprdep_table_base_directory            = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.recover_biprdep_table_base_directory))
        cls.log_bip_reports_table_directory                 = main_config_obj.json_val(JsonTagVariables.log_bip_reports_input_table_directory)
        cls.biprdep_tables_recover_status                   = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.biprdep_tables_recover_status))
        cls.table_etl_summary_recovered_flow_query          = log_config_obj.json_val(JsonTagVariables.table_etl_summary_recovered_flow_query)
        cls.table_etl_summary_normal_flow_query             = log_config_obj.json_val(JsonTagVariables.table_etl_summary_normal_flow_query)
        cls.table_etl_requestid_fetch_query                 = log_config_obj.json_val(JsonTagVariables.table_etl_requestid_fetch_query)
        cls.download_obj_requestid_fetch_query              = log_config_obj.json_val(JsonTagVariables.download_obj_requestid_fecth_query)
        cls.download_obj_summary_query                      = log_config_obj.json_val(JsonTagVariables.download_obj_summary_query)
        cls.overall_summary_query                           = log_config_obj.json_val(JsonTagVariables.overall_summary_query)  
        cls.overall_summary_boc_columns_to_expose           = log_config_obj.json_val(JsonTagVariables.overall_summary_boc_columns_to_expose)
        cls.table_level_log_input_query                     = log_config_obj.json_val(JsonTagVariables.table_level_log_input_query)
        cls.download_obj_level_log_input_query              = log_config_obj.json_val(JsonTagVariables.download_obj_level_log_input_query)
        cls.overall_etl_log_insert_query                    = log_config_obj.json_val(JsonTagVariables.overall_etl_log_insert_query)
        cls.sil_recovery_base_directory                     = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.sil_recovery_base_directory))
        cls.from_cloud_download_zip_directory               = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.from_cloud_download_zip_directory))
        cls.from_cloud_download_json_directory              = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.from_cloud_download_json_directory))
        cls.from_cloud_download_manifest_directory          = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.from_cloud_download_manifest_directory))
        cls.from_cloud_unzip_file_directory                 = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.from_cloud_unzip_file_directory))
        cls.mapping_vo_csv_directory                        = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.mapping_vo_csv_directory))
        cls.cloud_Connector_root_tag                        = cloudstorage_connection_config_obj.json_val(JsonTagVariables.cloud_Connector_root_tag)
        cls.dbconnectors                                    = dbconnection_config_obj.json_val(JsonTagVariables.connectors)
        cls.all_packages_log_level                          = log_config_obj.json_val(JsonTagVariables.allpackages_log_level)
        cls.fusion_job                                      = Fusionjobs_config_obj.json_val(JsonTagVariables.fusion_bicc_root_tag)
        cls.fusion_main_log_level                           = log_config_obj.json_val(JsonTagVariables.fusion_main_log_level)
        cls.thread_exec_log_level                           = log_config_obj.json_val(JsonTagVariables.thread_exec_log_level)
        cls.db_initialiser_log_level                        = log_config_obj.json_val(JsonTagVariables.db_initialiser_log_level)
        cls.json_value_extc_log_level                       = log_config_obj.json_val(JsonTagVariables.json_value_extc_log_level)
        cls.postgres_connection_pool_log_level              = log_config_obj.json_val(JsonTagVariables.postgres_connection_pool_log_level)
        cls.postgres_connector_log_level                    = log_config_obj.json_val(JsonTagVariables.postgres_connector_log_level)
        cls.csv_import_log_level                            = log_config_obj.json_val(JsonTagVariables.csv_import_log_level)
        cls.csv_import_ind_log_level                        = log_config_obj.json_val(JsonTagVariables.csv_import_ind_log_level)
        cls.oci_log_level                                   = log_config_obj.json_val(JsonTagVariables.oci_log_level)
        cls.cloud_storage_log_level                         = log_config_obj.json_val(JsonTagVariables.cloud_storage_log_level)
        cls.bicc_recover_log_level                          = log_config_obj.json_val(JsonTagVariables.bicc_recover_log_level)
        cls.bicc_down_job_log_level                         = log_config_obj.json_val(JsonTagVariables.bicc_down_job_log_level)
        cls.bicc_download_req_log_level                     = log_config_obj.json_val(JsonTagVariables.bicc_download_req_log_level)
        cls.bicc_util_log_level                             = log_config_obj.json_val(JsonTagVariables.bicc_util_log_level)
        cls.bicc_unzip_job_log_level                        = log_config_obj.json_val(JsonTagVariables.bicc_unzip_job_log_level)
        cls.file_util_log_level                             = log_config_obj.json_val(JsonTagVariables.file_util_log_level)
        cls.bicc_json_config_log_level                      = log_config_obj.json_val(JsonTagVariables.bicc_json_config_log_level)
        cls.bicc_processjob_log_level                       = log_config_obj.json_val(JsonTagVariables.bicc_processjob_log_level)
        cls.bicc_process_request_log_level                  = log_config_obj.json_val(JsonTagVariables.bicc_process_request_log_level)
        cls.bicc_process_csv_log_level                      = log_config_obj.json_val(JsonTagVariables.bicc_process_csv_log_level)
        cls.bicc_process_sil_log_level                      = log_config_obj.json_val(JsonTagVariables.bicc_process_sil_log_level)
        cls.bicc_download_process_log_level                 = log_config_obj.json_val(JsonTagVariables.bicc_download_process_log_level)
        cls.json_group_exec_log_level                       = log_config_obj.json_val(JsonTagVariables.json_group_exec_log_level)
        cls.json_sql_exec_log_level                         = log_config_obj.json_val(JsonTagVariables.json_sql_exec_log_level)
        cls.table_groups                                    = table_config_obj.json_val(JsonTagVariables.sil_table_root_tag)
        cls.vo_json_mf_merge_filename                       = main_config_obj.json_val(JsonTagVariables.vo_json_mf_merge_filename)
        cls.bicc_cloud_storage                              = main_config_obj.json_val(JsonTagVariables.bicc_cloud_storage)
        cls.run_status_directory                            = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.run_status_directory))
        cls.bicc_csv_process_config_directory               = StringUtility.derive_actual_directory(main_config_obj.json_val(JsonTagVariables.bicc_csv_process_config_directory))
        cls.bicc_csv_process_config_file                    = main_config_obj.json_val(JsonTagVariables.bicc_csv_process_config_file)
        cls.ora_instant_client_dir                          = main_config_obj.json_val(JsonTagVariables.ora_instant_client_dir)
        cls.oracle_connection_retry_count                   = main_config_obj.json_val(JsonTagVariables.connection_retry_count)
        cls.log_db_connection_name                          = log_config_obj.json_val(JsonTagVariables.use_logdb)
        cls.process_missing_view_objects_flag               = load_missing_view_object_config_obj.json_val(JsonTagVariables.process_missing_view_objects_flag)
        cls.missing_vo_csv_file_location                    = StringUtility.derive_actual_directory(load_missing_view_object_config_obj.json_val(JsonTagVariables.missing_vo_csv_file_location))
        cls.missing_vo_target_tables                        = load_missing_view_object_config_obj.json_val(JsonTagVariables.missing_vo_target_tables)
        cls.missing_vo_target_table_configuration_filepath  = StringUtility.derive_actual_directory(load_missing_view_object_config_obj.json_val(JsonTagVariables.missing_vo_target_table_configuration_filepath))
        cls.process_missing_view_objects_load_type          = load_missing_view_object_config_obj.json_val(JsonTagVariables.process_missing_view_objects_load_type)
        cls.process_missing_view_objects_group_id           = load_missing_view_object_config_obj.json_val(JsonTagVariables.process_missing_view_objects_group_id)
        cls.process_missing_view_objects_group_name         = load_missing_view_object_config_obj.json_val(JsonTagVariables.process_missing_view_objects_group_name)
        cls.missing_vo_process_csv_max_threads              = load_missing_view_object_config_obj.json_val(JsonTagVariables.missing_vo_process_csv_max_threads)
        cls.missing_vo_process_recovery_enable_flag         = load_missing_view_object_config_obj.json_val(JsonTagVariables.missing_vo_process_recovery_enable_flag)
        cls.wsdl_connection_parameters                      = load_missing_view_object_config_obj.json_val(JsonTagVariables.wsdl_connection_parameters)
        cls.process_missing_view_objects_WTTOFRSIM          = load_missing_view_object_config_obj.json_val(JsonTagVariables.process_missing_view_objects_WTTOFRSIM)
        cls.download_reports_soap_extension                 = load_missing_view_object_config_obj.json_val(JsonTagVariables.download_reports_soap_extension)
        cls.schedule_jobs_soap_extension                    = load_missing_view_object_config_obj.json_val(JsonTagVariables.schedule_jobs_soap_extension)
        cls.size_of_data_chunk_download                     = bipublisher_individual_report_config.json_val(JsonTagVariables.size_of_data_chunk_download)
        cls.flatten_xml_output                              = bipublisher_individual_report_config.json_val(JsonTagVariables.flatten_xml_output)
        cls.bypass_cache                                    = bipublisher_individual_report_config.json_val(JsonTagVariables.bypass_cache)
        cls.report_folder_path                              = bipublisher_individual_report_config.json_val(JsonTagVariables.report_folder_path)
        cls.report_export_format                            = bipublisher_individual_report_config.json_val(JsonTagVariables.report_export_format)
        cls.wsdl_connection_parameters                      = load_missing_view_object_config_obj.json_val(JsonTagVariables.wsdl_connection_parameters)
        cls.soap_request_xml_flag                           = load_missing_view_object_config_obj.json_val(JsonTagVariables.soap_request_xml_flag)
        cls.soap_request_xml_path                           = StringUtility.derive_actual_directory(load_missing_view_object_config_obj.json_val(JsonTagVariables.download_reports_xml_path))
        cls.fetch_request_status_xml_path                   = StringUtility.derive_actual_directory(load_missing_view_object_config_obj.json_val(JsonTagVariables.fetch_request_status_xml_path))
        cls.schedule_job_input_xml_path                     = StringUtility.derive_actual_directory(load_missing_view_object_config_obj.json_val(JsonTagVariables.schedule_job_input_xml_path))
        cls.bipreport_extract_incremental_hours_extract     = bipublisher_individual_report_config.json_val(JsonTagVariables.bipreport_extract_incremental_hours_extract)
        cls.target_table_reports                            = bipublisher_individual_report_config.json_val(JsonTagVariables.target_table_reports)
        cls.csv_import_flg                                  = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.csv_import_flg)
        cls.import_csv_files_location                       = StringUtility.derive_actual_directory(import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_files_location))
        cls.import_csv_sql_config_dir                       = StringUtility.derive_actual_directory(import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_sql_config_dir))
        cls.import_csv_load_type                            = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_load_type )
        cls.import_csv_group_id                             = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_group_id)
        cls.import_csv_group_name                           = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_group_name)
        cls.import_csv_process_max_threads                  = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_process_max_threads)
        cls.process_csv_list                                = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.process_csv_list )
        cls.import_csv_recovery_flg                         = import_etl_dependent_csv_config_obj.json_val(JsonTagVariables.import_csv_recovery_flg)
        cls.job_scheduling_parameter_inputs                 = job_scheduling_parameter_inputs.json_val(JsonTagVariables.job_scheduling_params)
        cls.default_bicc_ods_schema                         = main_config_obj.json_val(JsonTagVariables.default_bicc_ods_schema)
        cls.default_bicc_ods_stage_schema                   = main_config_obj.json_val(JsonTagVariables.default_bicc_ods_schema)
        cls.fusion_handle_multiple_bicc_instances           = Fusionjobs_config_obj.json_val(JsonTagVariables.fusion_handle_multiple_bicc_instances)